version: '3'
services:
  dev:
    build: .
    container_name: student-feedback
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./public:/app/public
      - ./styles:/app/styles
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      
    